{% set version = '0.1.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-recipes
  version: {{ version|replace("-", "_") }}

source:
  fn: recipes_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/recipes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/recipes/recipes_{{ version }}.tar.gz
  sha256: 56cbc96420e79ae07946c86d3a16a2f8fb56b29f22323c7e99621f410897912f

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-generics
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-matrix
    - r-purrr >=0.2.3
    - r-rcpproll
    - r-rlang >=0.3.0.1
    - r-tibble
    - r-tidyr
    - r-tidyselect >=0.1.1
    - r-timedate
    - r-withr
  run:
    - r-base
    - r-generics
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-matrix
    - r-purrr >=0.2.3
    - r-rcpproll
    - r-rlang >=0.3.0.1
    - r-tibble
    - r-tidyr
    - r-tidyselect >=0.1.1
    - r-timedate
    - r-withr

test:
  commands:
    - $R -e "library('recipes')"           # [not win]
    - "\"%R%\" -e \"library('recipes')\""  # [win]

about:
  home: https://github.com/topepo/recipes
  license: GPL-2
  summary: 'An extensible framework to create and preprocess  design matrices. Recipes consist
    of one or more data manipulation  and analysis "steps". Statistical parameters for
    the steps can  be estimated from an initial data set and then applied to  other
    data sets. The resulting design matrices can then be used  as inputs into statistical
    or machine learning models. '
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
