{% set version = '0.1.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-recipes
  version: {{ version|replace("-", "_") }}

source:
  fn: recipes_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/recipes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/recipes/recipes_{{ version }}.tar.gz
  sha256: be468f7b9b479e13785e90d239c4784679ad7648efd3d02cfc2a58a2fb1d10ef

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpproll
    - r-broom
    - r-ddalpha
    - r-dimred >=0.1.0
    - r-dplyr
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-pls
    - r-purrr >=0.2.3
    - r-rlang >=0.1.1
    - r-tibble
    - r-tidyr
    - r-tidyselect >=0.1.1
    - r-timedate
  run:
    - r-base
    - r-matrix
    - r-rcpproll
    - r-broom
    - r-ddalpha
    - r-dimred >=0.1.0
    - r-dplyr
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-pls
    - r-purrr >=0.2.3
    - r-rlang >=0.1.1
    - r-tibble
    - r-tidyr
    - r-tidyselect >=0.1.1
    - r-timedate

test:
  commands:
    - $R -e "library('recipes')"           # [not win]
    - "\"%R%\" -e \"library('recipes')\""  # [win]

about:
  home: https://github.com/topepo/recipes
  license: GPL-2
  summary: 'An extensible framework to create and preprocess  design matrices. Recipes consist
    of one or more data manipulation  and analysis "steps". Statistical parameters for
    the steps can  be estimated from an initial data set and then applied to  other
    data sets. The resulting design matrices can then be used  as inputs into statistical
    or machine learning models. '
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
