{% set version = '0.1.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-recipes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/recipes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/recipes/recipes_{{ version }}.tar.gz
  sha256: 56cbc96420e79ae07946c86d3a16a2f8fb56b29f22323c7e99621f410897912f

build:
  merge_build_host: True  # [win]
  number: 1001
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpproll
    - r-dplyr
    - r-generics
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-purrr >=0.2.3
    - r-rlang >=0.3.0.1
    - r-tibble
    - r-tidyr
    - r-tidyselect >=0.1.1
    - r-timedate
    - r-withr
  run:
    - r-base
    - r-matrix
    - r-rcpproll
    - r-dplyr
    - r-generics
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-purrr >=0.2.3
    - r-rlang >=0.3.0.1
    - r-tibble
    - r-tidyr
    - r-tidyselect >=0.1.1
    - r-timedate
    - r-withr

test:
  commands:
    - $R -e "library('recipes')"           # [not win]
    - "\"%R%\" -e \"library('recipes')\""  # [win]

about:
  home: https://github.com/tidymodels/recipes
  license: GPL-2
  summary: 'An extensible framework to create and preprocess  design matrices. Recipes consist
    of one or more data manipulation  and analysis "steps". Statistical parameters for
    the steps can  be estimated from an initial data set and then applied to  other
    data sets. The resulting design matrices can then be used  as inputs into statistical
    or machine learning models. '
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: recipes
# Title: Preprocessing Tools to Create Design Matrices
# Version: 0.1.4
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("RStudio", role = "cph"))
# Description: An extensible framework to create and preprocess  design matrices. Recipes consist of one or more data manipulation  and analysis "steps". Statistical parameters for the steps can  be estimated from an initial data set and then applied to  other data sets. The resulting design matrices can then be used  as inputs into statistical or machine learning models.
# URL: https://github.com/tidymodels/recipes
# BugReports: https://github.com/tidymodels/recipes/issues
# Depends: R (>= 3.1), dplyr
# Imports: generics, gower, ipred, lubridate, magrittr, Matrix, purrr (>= 0.2.3), RcppRoll, rlang (>= 0.3.0.1), stats, tibble, tidyr, tidyselect (>= 0.1.1), timeDate, utils, withr
# Suggests: covr, ddalpha, dimRed (>= 0.2.2), fastICA, ggplot2, igraph, kernlab, knitr, NMF, pls, RANN, rmarkdown, rpart, rsample, RSpectra, testthat
# License: GPL-2
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2018-11-18 19:44:24 UTC; max
# Author: Max Kuhn [aut, cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-11-19 12:50:03 UTC
