{% set version = "1.0.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-recipes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/recipes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/recipes/recipes_{{ version }}.tar.gz
  sha256: 42b2dcb25de4039dcb65e892f0026af267c96139e0ff018c666fc33d534b6e99

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-clock >=0.6.1
    - r-dplyr
    - r-ellipsis
    - r-generics >=0.1.2
    - r-glue
    - r-gower
    - r-hardhat >=1.2.0
    - r-ipred >=0.9_12
    - r-lifecycle >=1.0.3
    - r-lubridate >=1.8.0
    - r-magrittr
    - r-matrix
    - r-purrr >=0.2.3
    - r-rlang >=1.0.3
    - r-tibble
    - r-tidyr >=1.0.0
    - r-tidyselect >=1.2.0
    - r-timedate
    - r-vctrs >=0.5.0
    - r-withr
  run:
    - r-base
    - r-cli
    - r-clock >=0.6.1
    - r-dplyr
    - r-ellipsis
    - r-generics >=0.1.2
    - r-glue
    - r-gower
    - r-hardhat >=1.2.0
    - r-ipred >=0.9_12
    - r-lifecycle >=1.0.3
    - r-lubridate >=1.8.0
    - r-magrittr
    - r-matrix
    - r-purrr >=0.2.3
    - r-rlang >=1.0.3
    - r-tibble
    - r-tidyr >=1.0.0
    - r-tidyselect >=1.2.0
    - r-timedate
    - r-vctrs >=0.5.0
    - r-withr

test:
  commands:
    - $R -e "library('recipes')"           # [not win]
    - "\"%R%\" -e \"library('recipes')\""  # [win]

about:
  home: https://recipes.tidymodels.org
  dev_url: https://github.com/tidymodels/recipes
  doc_url: https://recipes.tidymodels.org/reference/index.html
  license: MIT
  summary: 'An extensible framework to create and preprocess  design matrices. Recipes consist of one or more data manipulation  and analysis "steps". Statistical parameters for the steps can  be estimated from an initial data set and then applied to  other data sets. The resulting design matrices can then be used  as inputs
    into statistical or machine learning models. '
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
