{% set version = "0.1.13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-recipes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/recipes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/recipes/recipes_{{ version }}.tar.gz
  sha256: 7afd470a274904dd0dd6c7c187cf73c771fa0bbd94e082e9e1c0fc38f3ad77b4

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-dplyr
    - r-generics
    - r-glue
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-purrr >=0.2.3
    - r-rlang >=0.4.0
    - r-tibble
    - r-tidyr
    - r-tidyselect >=0.2.5
    - r-timedate
    - r-withr
  run:
    - r-base
    - r-matrix
    - r-dplyr
    - r-generics
    - r-glue
    - r-gower
    - r-ipred
    - r-lubridate
    - r-magrittr
    - r-purrr >=0.2.3
    - r-rlang >=0.4.0
    - r-tibble
    - r-tidyr
    - r-tidyselect >=0.2.5
    - r-timedate
    - r-withr

test:
  commands:
    - $R -e "library('recipes')"           # [not win]
    - "\"%R%\" -e \"library('recipes')\""  # [win]

about:
  home: https://github.com/tidymodels/recipes
  license: GPL-2
  summary: 'An extensible framework to create and preprocess  design matrices. Recipes consist of one or more data manipulation  and analysis "steps". Statistical parameters for the steps can  be estimated from an initial data set and then applied to  other data sets. The resulting design matrices can then be used  as inputs
    into statistical or machine learning models. '
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: recipes
# Title: Preprocessing Tools to Create Design Matrices
# Version: 0.1.6
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("RStudio", role = "cph"))
# Description: An extensible framework to create and preprocess  design matrices. Recipes consist of one or more data manipulation  and analysis "steps". Statistical parameters for the steps can  be estimated from an initial data set and then applied to  other data sets. The resulting design matrices can then be used  as inputs into statistical or machine learning models.
# URL: https://github.com/tidymodels/recipes
# BugReports: https://github.com/tidymodels/recipes/issues
# Depends: R (>= 3.1), dplyr
# Imports: generics, glue, gower, ipred, lubridate, magrittr, Matrix, purrr (>= 0.2.3), rlang (>= 0.4.0), stats, tibble, tidyr, tidyselect (>= 0.2.5), timeDate, utils, withr
# Suggests: covr, ddalpha, dimRed (>= 0.2.2), fastICA, ggplot2, igraph, kernlab, knitr, pls, RANN, RcppRoll, rmarkdown, rpart, rsample, RSpectra, testthat
# License: GPL-2
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-02 20:22:11 UTC; max
# Author: Max Kuhn [aut, cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Max Kuhn <max@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-07-02 21:20:05 UTC
