appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: yzTkvGp5nre82P1Dy/y2KosUiNC5CmVKE/LVbsW27FxxRk5snmIBnVezTHzmL0LGOFuGgfBi0QFKtaRltHGrWtwYl4qu0T3JdG4LV7fv4613zpA6AnmEYTEeEcR6XnNUUFuKS31ViA9FpmkIwE9z5SLjoA+n74i7bAqT62SiF64SpLR9+7NfJAhgpPU3plMqrwAgKsAK3qMc+3LShdgDuaIlkiCjFvT/8o6BkjwnGPCl6LvD4kBI9T+MaqH27n35v+ITaqPxXObUcnFOni/Xw+FHLnuW8W9MDIy5X0gmzauK7p6Jtsdg5Y8sLrmkEvsvUkIckqiNVEC2fVQM0Y05fUtg2KjSySQhJkL1oTMKXPhZIsU2LLV7UftrGiVmM8iSt+2iVV2dAAeMHmDJqxUOPZaUXS0qp4fW2lThsUlWR8r59vVwPEcPQC0ViuMXX44i6larl0jfDGODgxpu+ZlOUxU70YnGi15AMAMqbUH0KImfQEvbtUxSid02e9FLl03lTt/sfKHfNRF8WXiD2Llc9C7eA4+L88v6EXmfofEmD0pJNdC0mW+YpOnivx6W/d6xCrHZC/ZY1y/adDRV53ZbdFWO3PlleqQzFwgKz3aJgeTITif4xPvWrn8DdjpV8CKgUlk7ONv1l1bOQ+I4Rh2KagfJa4iYUl0Nj7EAHDidMMU=}
